services:
  postgres:
    image: postgres:15
    container_name: pg_websearch
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: websearch
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_websearch
    restart: unless-stopped
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  mysql:
    image: mysql:8
    container_name: mysql8-qiniu
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123
      MYSQL_DATABASE: Qiniu_Project
      MYSQL_USER: Qiniu
      MYSQL_PASSWORD: 20250922
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql            # 数据持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 初始化 SQL 脚本